config/routes.rb
Rails.application.routes.draw do
  get 'questions/top'
  root 'pages#index' 
  #　root でトップページのリンク先を指定する
  
  get 'sessions/new'
  
  get 'kindles/search'
  
  get 'favorites/top'
  get 'favorites/search' 
  get 'favorites/index'
  post 'favorites/:id/destroy' => 'favorites#destroy'
  
  get 'book_shelfs/top'
  get 'book_shelfs/search'

  post 'purchaseds/:book_id/state' => 'book_shelfs#state'
  post 'purchaseds/:book_id/default' => 'book_shelfs#default'
  post 'purchaseds/:book_id/destroy' => 'book_shelfs#destroy'

  get 'questions/top'
  get 'pages/index'
  
  resources :users
  resources :favorites
  resources :purchaseds
  resources :reeds
  resources :stores
  resources :sale_books
  resources :questions
  resources :book_shelfs
  
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  has_many :sale_books
  has_many :stores, through: :sale_books
  has_many :favorites
  has_many :favorite_users, through: :favorites, source: 'user'
  has_many :purchaseds
  has_many :purchased_users, through: :purchaseds, source: 'user'
  has_many :reads
  has_many :reed_users, through: :reeds, source: 'user'
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :book
  belongs_to :user
end

app/models/purchased.rb
class Purchased < ApplicationRecord
  belongs_to :book
  belongs_to :user
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :user
end

app/models/reed.rb
class Reed < ApplicationRecord
  belongs_to :book
  belongs_to :user
end

app/models/sale_book.rb
class SaleBook < ApplicationRecord
  belongs_to :book
  belongs_to :store
end

app/models/store.rb
class Store < ApplicationRecord
  has_one :sale_book
end

app/models/user.rb
class User < ApplicationRecord
  validates :password, presence: true
  validates :email, presence: true, format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }
  validates :name, presence: true
  
  has_many :favorites
  has_many :favorite_books, through: :favorites, source: 'book'
  has_many :purchaseds
  has_many :purchased_books, through: :purchaseds, source: 'book'
  has_many :reads
  has_many :reed_books, through: :reeds, source: 'book'
  has_many :quentions
  
  has_secure_password
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  before_action :ensure_correct_user, {only: [:top, :index]}
  
  def top
    @favorite_books = current_user.favorite_books
  end
  
  def index
    @favorite_books = current_user.favorite_books
    
    @q = @favorite_books.ransack(params[:q])
    @favorite_books = @q.result(distinct: true)
  end
  
  def destroy
    favorite = Favorite.find_by(user_id: current_user.id,book_id: params[:id])
    favorite.destroy
    
    redirect_to("/favorites/index")
  end
  
  def search
    @favorite_books = current_user.favorite_books || []
    @books = []
    
    @title = params[:title]
    if @title.present?
      results = RakutenWebService::Books::Book.search({
        title: @title,
        hits: 20,
      })

      results.each do |result|
        book = read(result)
        @books << book
      end
    end
  end

  def create
    @book = Book.find_or_initialize_by(isbn: params[:isbn])

    unless @book.persisted?
      results = RakutenWebService::Books::Book.search(isbn: @book.isbn)
      @book = Book.new(read(results.first))
      @book.save
    end

    favorite = Favorite.new(user_id: current_user.id, book_id: @book.id)
    favorite.save
      redirect_to "/favorites/search"

  end

  private
  def read(result)
    image_url = result['largeImageUrl']#.gsub('?_ex=200x200', '')
    title = result['title']
    publisherName = result['publisherName']
    author = result['author']
    isbn = result['isbn']
    itemPrice = result['itemPrice']
    url = result['itemUrl']
    
    {
      image_url: image_url,
      title: title,
      publisherName: publisherName,
      author: author,
      isbn: isbn,
      itemPrice: itemPrice,
      url: url,
    }
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
    @books = Book.all
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
  
  def create
    user = User.find_by(email: params[:session][:email])
    if user && user.authenticate(params[:session][:password])
      log_in user
      redirect_to root_path, success: 'ログインに成功しました'
    else
      flash.now[:danger] = 'ログインに失敗しました'
      render :new
    end
  end
  
  def destroy
    log_out
    redirect_to root_url, info: 'ログアウトしました'
  end

  private
  def log_in(user)
    session[:user_id] = user.id
  end
  
  def log_out
    session.delete(:user_id)
    @current_user = nil
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to root_path, success: '登録が完了しました'
    else
      flash.now[:danger] = "登録に失敗しました"
      render :new
    end
  end
  
  private
  def user_params
    params.require(:user).permit(:name,:email, :password, :password_confirmtion)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

end

app/helpers/book_shelf_helper.rb
module BookShelfHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
  
end

app/helpers/kindles_helper.rb
module KindlesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/sale_book_helper.rb
module SaleBookHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/favorites/_favorites.html.erb
<div class="bs-component">
  <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
  
    <div class="collapse navbar-collapse" id="navbarColor01">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item">
          <%= link_to 'セール中の書籍', favorites_top_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to '登録書籍一覧', favorites_index_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to '書籍を探す', favorites_search_path, class: "nav-link" %>
        </li>
      </ul>
    </div>
  </nav>
</div>

app/views/favorites/index.html.erb
<div class="bs-component">
  <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
    <div class="collapse navbar-collapse" id="navbarColor01">
      <%= search_form_for @q, class: 'form-inline my-2 my-lg-0', url: favorites_index_path do |f| %>
        <%= f.search_field :title_cont, class: 'form-control mr-sm-2', placeholder:'お気に入りした書籍を検索', size: 30 %>
        <%= f.submit "検索", class: "btn btn-secondary my-2 my-sm-0" %>
      <% end %>
    </div>
  </nav>
</div>

<div class="container-fluid">
  <% @favorite_books.each do |book| %>
    <div class="row book">
      <div class="col-md-3 image">
        <img src="<%= book[:image_url] %>" class="img-fluid" alt="">
      </div>
      <div class="col-md-6">
        <div class="text">
          <div><h4><%= book[:title] %></h4></div>
          <div><%= "出版社: #{book[:publisherName]}" %></div>
          <div><%= "著者: #{book[:author]}" %></div>
          <div><%= "ISBN: #{book[:isbn]}" %></div>
          <div><%= "価格:￥#{book[:itemPrice]}" %></div>
        </div>
      </div>
      <div class="col-md-3">
        <div class="text">
          <%= link_to "削除", "/favorites/#{book.id}/destroy", method: "post", class: "btn btn-primary" %>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/favorites/search.html.erb
<div class="bs-component">
  <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
    <div class="collapse navbar-collapse" id="navbarColor01">
      <%= form_tag(favorites_search_path, method: :get, class: 'form-inline my-2 my-lg-0') do %>
        <%= text_field_tag :title, @title, class: 'form-control mr-sm-2', placeholder:'お気に入りする書籍を検索', size: 30 %>
        <%= submit_tag '検索', class: "btn btn-secondary my-2 my-sm-0" %>
      <% end %>
    </div>
  </nav>
</div>

<div class="container-fluid">
  <% @books.each do |book| %>
    <div class="row book">
      <div class="col-md-3 image">
        <img src="<%= book[:image_url] %>" class="img-fluid" alt="">
      </div>
      <div class="col-md-6">
        <div class= "text">
          <div><h4><%= book[:title] %></h4></div>
          <div><%= "出版社: #{book[:publisherName]}" %></div>
          <div><%= "著者: #{book[:author]}" %></div>
          <div><%= "ISBN: #{book[:isbn]}" %></div>
          <div><%= "価格:￥#{book[:itemPrice]}" %></div>
        </div>
      </div>
      <div class="col-md-3">
        <% if @favorite_books.map(&:isbn).include?(book[:isbn]) %>
          <div class="button">
            <button class = "btn btn-primary" disabled >お気に入りに追加済み</ button>
          </div>
        <% else %>
        <div class="text">
          <%= form_tag(favorites_path, method: :post) do %>
            <%= hidden_field_tag :isbn, book[:isbn] %>
            <%= submit_tag 'お気に入り書籍に追加', class: "btn btn-primary" %>
          <% end %>
        </div>
        <% end %>
      </div>
    </div>
  <% end %>
</div>

app/views/favorites/top.html.erb
<div class="container-fluid"> 
  <% @favorite_books.each do |favo_book| %>
    <% if favo_book.stores.present?%>
      <div class="row book">
        <div class="col-md-3 image">
          <img src="<%= favo_book[:image_url] %>" class="img-fluid" alt="">
        </div>
        <div class="col-md-9">
          <div class="text">
            <div><h4><%= favo_book[:title] %></h4></div>
            <div><%= "出版社: #{favo_book[:publisherName]}" %></div>
            <div><%= "著者: #{favo_book[:author]}" %></div>
            <div><%= "ISBN: #{favo_book[:isbn]}" %></div>
            <% favo_book.stores.each do |store| %>
              <%= "特価: #{store.name} "%>
              <%= store.itemPrice %>
            <% end %>
          </div>
        </div>
      </div>
    <% end %>
  <% end %>
</div>

app/views/users/new.html.erb
<div class="container">
  <div class="row">
    <div class="offset-md-3 col-md-6">
      <%= form_for @user do |f| %>
        <div class="form-group">
          <%= f.label :名前, class: 'text-white' %>
          <%= f.text_field :name, class: 'form-control', placeholder:"名前" %>
        </div>
        <div class="form-group">
          <%= f.label :メールアドレス, class: 'text-white' %>
          <%= f.text_field :email, class: 'form-control', placeholder:"メールアドレス" %>
        </div>
        <div class="form-group">
          <%= f.label :パスワード, class: 'text-white' %>
          <%= f.password_field :password, class: 'form-control', placeholder:"パスワード" %>
        </div>
        <div class="form-group">
          <%= f.label :パスワード（確認）, class: 'text-white' %>
          <%= f.password_field :password_confirmation, class: 'form-control', placeholder:"パスワード（確認）" %>
        </div>
        <%= f.submit "登録", class: 'btn btn-primary btn-lg btn-block' %>
      <% end %>
      <p class="text-right"><%= link_to 'ログインはこちら', login_path %> </p>
    </div>
  </div>
</div>