config/routes.rb
Rails.application.routes.draw do
  get 'questions/top'
  root 'pages#index' 
  #　root でトップページのリンク先を指定する
  
  get 'sessions/new'
  
  get 'kindles/search'
  
  get 'favorites/top'
  get 'favorites/search' 
  get 'favorites/index'
  post 'favorites/:id/destroy' => 'favorites#destroy'
  
  get 'book_shelfs/top'
  get 'book_shelfs/search'

  post 'purchaseds/:book_id/state' => 'book_shelfs#state'
  post 'purchaseds/:book_id/default' => 'book_shelfs#default'
  post 'purchaseds/:book_id/destroy' => 'book_shelfs#destroy'

  get 'questions/top'
  get 'pages/index'
  
  resources :users
  resources :favorites
  resources :purchaseds
  resources :reeds
  resources :stores
  resources :sale_books
  resources :questions
  resources :book_shelfs
  
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  has_many :sale_books
  has_many :stores, through: :sale_books
  has_many :favorites
  has_many :favorite_users, through: :favorites, source: 'user'
  has_many :purchaseds
  has_many :purchased_users, through: :purchaseds, source: 'user'
  has_many :reads
  has_many :reed_users, through: :reeds, source: 'user'
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :book
  belongs_to :user
end

app/models/purchased.rb
class Purchased < ApplicationRecord
  belongs_to :book
  belongs_to :user
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :user
end

app/models/reed.rb
class Reed < ApplicationRecord
  belongs_to :book
  belongs_to :user
end

app/models/sale_book.rb
class SaleBook < ApplicationRecord
  belongs_to :book
  belongs_to :store
end

app/models/store.rb
class Store < ApplicationRecord
  has_one :sale_book
end

app/models/user.rb
class User < ApplicationRecord
  validates :password, presence: true
  validates :email, presence: true, format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }
  validates :name, presence: true
  
  has_many :favorites
  has_many :favorite_books, through: :favorites, source: 'book'
  has_many :purchaseds
  has_many :purchased_books, through: :purchaseds, source: 'book'
  has_many :reads
  has_many :reed_books, through: :reeds, source: 'book'
  has_many :quentions
  
  has_secure_password
end

app/controllers/book_shelfs_controller.rb
class BookShelfsController < ApplicationController
  before_action :ensure_correct_user, {only: [:top, :search]}
  
  def top
    @purchased_books = current_user.purchased_books
    
    @q = @purchased_books.ransack(params[:q])
    @purchased_books = @q.result(distinct: true)
  end
  
  def destroy
    purchased = Purchased.find_by(user_id: current_user.id,book_id: params[:book_id])
    purchased.destroy
    
    redirect_to("/book_shelfs/top")
  end
  
  def state
    reed = Reed.new(user_id: current_user.id, book_id: params[:book_id])
    reed.save
    
    redirect_to("/book_shelfs/top")
  end
  
  def default
    reed = Reed.find_by(user_id: current_user.id, book_id: params[:book_id])
    reed.destroy
    
    redirect_to("/book_shelfs/top")
  end
  
  def search
    @purchased_books = current_user.purchased_books
    @books = []
    
    @title = params[:title]
    if @title.present?
      results = RakutenWebService::Books::Book.search({
        title: @title,
        hits: 20,
      })

      results.each do |result|
        book = read(result)
        @books << book
      end
    end
  end

  def create
    @book = Book.find_or_initialize_by(isbn: params[:isbn])

    unless @book.persisted?
      results = RakutenWebService::Books::Book.search(isbn: @book.isbn)
      @book = Book.new(read(results.first))
      @book.save
    end
    
    purchased = Purchased.new(user_id: current_user.id, book_id: @book.id)
    purchased.save
      redirect_to "/book_shelfs/search"

  end

  private
  def read(result)
    image_url = result['largeImageUrl']#.gsub('?_ex=200x200', '')
    title = result['title']
    publisherName = result['publisherName']
    author = result['author']
    isbn = result['isbn']
    itemPrice = result['itemPrice']
    url = result['itemUrl']
    
    {
      image_url: image_url,
      title: title,
      publisherName: publisherName,
      author: author,
      isbn: isbn,
      itemPrice: itemPrice,
      url: url,
    }

  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
    @books = Book.all
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to root_path, success: '登録が完了しました'
    else
      flash.now[:danger] = "登録に失敗しました"
      render :new
    end
  end
  
  private
  def user_params
    params.require(:user).permit(:name,:email, :password, :password_confirmtion)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

end

app/helpers/book_shelf_helper.rb
module BookShelfHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
  
end

app/helpers/kindles_helper.rb
module KindlesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/sale_book_helper.rb
module SaleBookHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/book_shelfs/_book_shelf.html.erb
<div class="bs-component">
  <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
  
    <div class="collapse navbar-collapse" id="navbarColor01">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item">
          <%= link_to '所有している書籍', book_shelfs_top_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to '書籍を探す', book_shelfs_search_path, class: "nav-link" %>
        </li>
      </ul>
      <%= search_form_for @q, class: 'form-inline my-2 my-lg-0', url: favorites_index_path do |f| %>
        <%= f.search_field :title_cont, class: 'form-control mr-sm-2', placeholder:'お気に入りした書籍を検索', size: 30 %>
        <%= f.submit "検索", class: "btn btn-secondary my-2 my-sm-0" %>
      <% end %>
    </div>
  </nav>
</div>

app/views/book_shelfs/search.html.erb
<div class="bs-component">
  <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
    <div class="collapse navbar-collapse" id="navbarColor01">
      <%= form_tag(book_shelfs_search_path, method: :get, class: 'form-inline my-2 my-lg-0') do %>
        <%= text_field_tag :title, @title, class: 'form-control mr-sm-2', placeholder:'購入した書籍を検索', size: 30 %>
        <%= submit_tag '検索', class: "btn btn-secondary my-2 my-sm-0" %>
      <% end %>
    </div>
  </nav>
</div>

<div class="container-fluid">
  <% @books.each do |book| %>
    <div class="row book">
      <div class="col-md-3 image">
        <img src="<%= book[:image_url] %>" class="img-fluid" alt="">
      </div>
      <div class="col-md-6">
        <div class="text">
          <div><h4><%= book[:title] %></h4></div>
          <div><%= "出版社: #{book[:publisherName]}" %></div>
          <div><%= "著者: #{book[:author]}" %></div>
          <div><%= "ISBN: #{book[:isbn]}" %></div>
          <div><%= "価格:￥#{book[:itemPrice]}" %></div>
        </div>
      </div>
      <div class="col-md-3">
        <% if @purchased_books.map(&:isbn).include?(book[:isbn]) %>
          <div class="text">
            <button class = "btn btn-primary" disabled >購入済み書籍に追加済み</ button>
          </div>
        <% else %>
        <div class="text">
          <%= form_tag(book_shelfs_path, method: :post) do %>
            <%= hidden_field_tag :isbn, book[:isbn] %>
            <%= submit_tag '購入済み書籍に追加', class: "btn btn-primary" %>
          <% end %>
        </div>
        <% end %>
      </div>
    </div>
  <% end %>
</div>

app/views/book_shelfs/top.html.erb
<div class="bs-component">
  <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
    <div class="collapse navbar-collapse" id="navbarColor01">
      <%= search_form_for @q, class: 'form-inline my-2 my-lg-0', url: book_shelfs_top_path do |f| %>
        <%= f.search_field :title_cont, class: 'form-control mr-sm-2', placeholder:'所有している書籍を検索', size: 30 %>
        <%= f.submit "検索", class: "btn btn-secondary my-2 my-sm-0" %>
      <% end %>
    </div>
  </nav>
</div>
<div class="container-fluid">
  <% @purchased_books.each do |book| %>
    <div class="row book">
      <div class="col-md-3 image">
        <img src="<%= book[:image_url] %>" class="img-fluid" alt="">
      </div>
      <div class="col-md-6">
        <div class="text">
          <div><h4><%= book[:title] %></h4></div>
          <div><%= "出版社: #{book[:publisherName]}" %></div>
          <div><%= "著者: #{book[:author]}" %></div>
          <div><%= "ISBN: #{book[:isbn]}" %></div>
        </div>
      </div>
      <div class="col-md-3">
        <div class="text">
          <% if Reed.find_by(user_id: current_user.id, book_id: book.id)%>
            <%= link_to("未読にする", "/purchaseds/#{book.id}/default", method: "post", class: "btn btn-success") %>
          <% else %>
            <%= link_to("既読にする", "/purchaseds/#{book.id}/state", method: "post", class: "btn") %>
          <% end %>
          <%= link_to("削除", "/purchaseds/#{book.id}/destroy", method: "post", class: "btn btn-primary") %>
        </div>
      </div>
    </div>
  <% end %>
</div>