config/routes.rb
Rails.application.routes.draw do
  get 'questions/top'
  root 'pages#index' 
  #　root でトップページのリンク先を指定する
  
  get 'sessions/new'
  
  get 'kindles/search'
  
  get 'favorites/top'
  get 'favorites/search' 
  get 'favorites/index'
  post 'favorites/:id/destroy' => 'favorites#destroy'
  
  get 'book_shelfs/top'
  get 'book_shelfs/search'

  post 'purchaseds/:book_id/state' => 'book_shelfs#state'
  post 'purchaseds/:book_id/default' => 'book_shelfs#default'
  post 'purchaseds/:book_id/destroy' => 'book_shelfs#destroy'

  get 'questions/top'
  get 'pages/index'
  
  resources :users
  resources :favorites
  resources :purchaseds
  resources :reeds
  resources :stores
  resources :sale_books
  resources :questions
  resources :book_shelfs
  
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  has_many :sale_books
  has_many :stores, through: :sale_books
  has_many :favorites
  has_many :favorite_users, through: :favorites, source: 'user'
  has_many :purchaseds
  has_many :purchased_users, through: :purchaseds, source: 'user'
  has_many :reads
  has_many :reed_users, through: :reeds, source: 'user'
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :book
  belongs_to :user
end

app/models/purchased.rb
class Purchased < ApplicationRecord
  belongs_to :book
  belongs_to :user
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :user
end

app/models/reed.rb
class Reed < ApplicationRecord
  belongs_to :book
  belongs_to :user
end

app/models/sale_book.rb
class SaleBook < ApplicationRecord
  belongs_to :book
  belongs_to :store
end

app/models/store.rb
class Store < ApplicationRecord
  has_one :sale_book
end

app/models/user.rb
class User < ApplicationRecord
  validates :password, presence: true
  validates :email, presence: true, format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }
  validates :name, presence: true
  
  has_many :favorites
  has_many :favorite_books, through: :favorites, source: 'book'
  has_many :purchaseds
  has_many :purchased_books, through: :purchaseds, source: 'book'
  has_many :reads
  has_many :reed_books, through: :reeds, source: 'book'
  has_many :quentions
  
  has_secure_password
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
    @books = Book.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

end

app/helpers/book_shelf_helper.rb
module BookShelfHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
  
end

app/helpers/kindles_helper.rb
module KindlesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/sale_book_helper.rb
module SaleBookHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BookWindow</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    
    <script src="https://kit.fontawesome.com/d15b5c6f7c.js"></script>
    
  </head>

  <body>
    
    <% flash.each do |key, value| %>
      <div class="alert alert-<%= key %>" role="alert"><%= value %></div>
    <% end %>
    
    <header>
      <div class="bs-component">
        <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
          <%= link_to 'ホーム', pages_index_path, class: "navbar-brand" %>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
        
          <div class="collapse navbar-collapse" id="navbarColor01">
            <ul class="navbar-nav mr-auto">
              <% unless logged_in?%>
                <li class="nav-item">
                  <%= link_to 'ログイン', login_path, class: "nav-link" %>
                </li>
                <li class="nav-item">
                  <%= link_to 'サインアップ', new_user_path, class: "nav-link" %>
                </li>
              <% end %>
              <% if logged_in?%>
                <li class="nav-item">
                  <%= link_to 'ログアウト', logout_path, method: :delete, class: "nav-link" %>
                </li>
                <li class="nav-item dropdown">
                  <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    お気に入り
                  </a>
                  <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <%= link_to 'セール中の書籍', favorites_top_path, class: "dropdown-item" %>
                    <%= link_to '登録書籍一覧', favorites_index_path, class: "dropdown-item" %>
                    <%= link_to '書籍を探す', favorites_search_path, class: "dropdown-item" %>
                  </div>
                </li>
                <li class="nav-item dropdown">
                  <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    所有している書籍
                  </a>
                  <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <%= link_to '所有している書籍', book_shelfs_top_path, class: "dropdown-item" %>
                    <%= link_to '書籍を探す', book_shelfs_search_path, class: "dropdown-item" %>
                  </div>
                </li>
                <!--<li class="nav-item">-->
                <!--  <%= link_to '問い合わせ', questions_top_path, class: "nav-link" %>-->
                <!--</li>-->
              <% end %>
            </ul>
          </div>
        </nav>
      </div>
    </header>
    
    <%= yield %>
    
    <script>
      $(function(){
        $(".alert").fadeOut(3000);
      });
    </script>
    
  </body>
</html>

app/views/pages/index.html.erb
<div class="container-fluid">
  <div class="top-hero-wrapper text-center">
    <h1>セール書籍一覧</h1>
  </div>
  
  <% @books.each do |book| %>
    <% if book.stores.present?%>
      <div class="row book">
        <div class="col-md-3 image">
          <img src="<%= book[:image_url] %>" class="img-fluid" alt="">
        </div>
        <div class="col-md-9">
          <div class="text">
            <div><h4><%= book[:title] %></h4></div>
            <div><%= "出版社: #{book[:publisherName]}" %></div>
            <div><%= "著者: #{book[:author]}" %></div>
            <div><%= "ISBN: #{book[:isbn]}" %></div>
            <% book.stores.each do |store| %>
              <%= "特価: #{store.name} "%>
              <%= store.itemPrice %>
            <% end %>
          </div>
        </div>
      </div>
    <% end %>
  <% end %>
</div>